### PR TITLE
New Icon?

### PR DESCRIPTION
**Pull request by WhatDamon**
Personally subjective view of the current icon is rather strange, visually disjointed.
The new icon in this PR have been redesigned using PowerPoint and Photoshop, and the look and feel may be better?
_Note: This PR also modified the `.gitignore` file to avoid the `.vs` folder generated by Visual Studio to be uploaded._
***
Icon design file：
[uwidget.pptx](https://github.com/user-attachments/files/16637035/uwidget.pptx)
Icon borders from [Apple Developer's section on Design](https://developer.apple.com/design/)

### CODE REVIEW

**Comment by creewick** [comment]
I knew the current icon is temporary, but I didn't supposed it would be requested to change that soon 😅

I like the one you made, it looks more clean and minimalistic.
Don't you mind, if I use your icon with some small adjustments?

I want to re-create it in `.psd` format for future usage, include dark theme icon, and maybe move elements a little bit.
I will do it as part of this pull request, and merge it when I'm ready

**Comment by WhatDamon** [comment]
> I knew the current icon is temporary, but I didn't supposed it would be requested to change that soon 😅
> 
> I like the one you made, it looks more clean and minimalistic. Don't you mind, if I use your icon with some small adjustments?
> 
> I want to re-create it in `.psd` format for future usage, include dark theme icon, and maybe move elements a little bit. I will do it as part of this pull request, and merge it when I'm ready

I don't mind. Feel free to change it. 😅

**Comment by creewick** [comment]
I drew some more options. What do you think?

image
image<br><br>
image
image<br><br>
image
image<br><br>
image
image

### References

**Comment by WhatDamon** [comment]
> I drew some more options. What do you think?
> 
> image image
> 
> image image
> 
> image image
> 
> image image
> ### References
>   

It looks quite good, especially the left part looks **quite recognizable in the taskbar where the icons are smaller**, but I think it's greater to **combine the design of these icons with the design of the icons currently in use**, or else it still looks too much like the design of Apple's existing software icons.
If possible, I personally think that **the 256px large icons can be used in the right version**, retaining as much detail as possible, and if there is a second row of icons of the depth of field effect, the feeling will be even better!
It's up to you to decide how to improve it. Good luck! 😘

**Pull request merged**
