### PR TITLE
Add Chinese language support

### PR DESCRIPTION
**Pull request by suntrise**
Hello, I am a Chinese.
I like your project so much that I added Chinese language support to it.
Hope everything goes well with your project.

### CODE REVIEW

**Comment by creewick** [comment]
Hi! Thanks for your effort and for your feedback!
I will take a look at it soon

**Comment by WhatDamon** [comment]
this is simplified chinese, and the default font is strange for mainland chinese, i suggest using `Microsoft YaHei` as the default font under windows
of course, you can also consider embedded fonts

**Comment by creewick** [comment]
@WhatDamon 
There will be support of embedded fonts in the future. Some users want to see `Segoe UI` for more Window-ish look. 
I will keep in mind to add `Microsoft YaHei` as well.

**Comment by creewick** [comment]
@suntrise 
I will take a closer look at the branch next week.
But I see right now, that a lot of files have white-space changes only.
Would you mind to revert these changes? It would be perfect if the branch would only contains changes for `Locale.*` files

If not, I can make it when I have time.
Thank you

**Comment by creewick** [comment]
@WhatDamon 
I'm currently working on using system fonts in the app.
Please tell me, should I change app's font automatically to "Microsoft YaHei" when Chinese language is selected?

**Comment by creewick** [comment]
It would be available anyway, but I guess I can save several clicks for the user

Screenshot 2024-08-17 at 6 38 18 PM

**Comment by WhatDamon** [comment]
[b4b2992](https://github.com/creewick/uWidgets/commit/b4b299204e0ad923fe60c4615c43c2fde68bfe67) still have typeface problem while using Chinese

image

Currently this font may be more in line with Traditional Chinese font style, but for Traditional Chinese, Microsoft JhengHei font may be more suitable, there are plans to split `zh` into `zh-Hans` (Simplified Chinese, i.e. current `zh`) and `zh-Hant` (Traditional Chinese)

If Japanese support is added in the future, it is also recommended to talk to native Japanese speakers about fonts, as there are a lot of variant kanji in Japanese, which occupy the same Unicode code points as Chinese characters

**Comment by creewick** [comment]
Got it! The font selector is still in development, but may be released soon.

As for automatic changing of font, I will leave this for the future discussion.
I guess, a simple mapping from the language code to font name could be done

`zh-Hans` → `Microsoft YaHei`, 
`zh-Hant` → `Microsoft JhengHei`,
and so on..

**Pull request closed without merging**
